#Zybo Zynq constraint file AD1DA2JE.xdc
#ECE3622 
#c 2019 Dennis Silage

#Clock signal
set_property PACKAGE_PIN L16 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
create_clock -add -name sys_clk_pin -period 8.00 -waveform {0 4} [get_ports CLK]

#Switches
#set_property PACKAGE_PIN G15 [get_ports {SW0}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SW0}]
#set_property PACKAGE_PIN P15 [get_ports {SW1}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SW1}]
#set_property PACKAGE_PIN W13 [get_ports {SW2}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SW2}]
#set_property PACKAGE_PIN T16 [get_ports {SW3]
#set_property IOSTANDARD LVCMOS33 [get_ports {SW3}]

#Buttons
#set_property PACKAGE_PIN R18 [get_ports {BTN0}]
#set_property IOSTANDARD LVCMOS33 [get_ports {BTN0}]
#set_property PACKAGE_PIN P16 [get_ports {BTN1]
#set_property IOSTANDARD LVCMOS33 [get_ports {BTN1}]
#set_property PACKAGE_PIN V16 [get_ports {BTN2}]
#set_property IOSTANDARD LVCMOS33 [get_ports {BTN2}]
#set_property PACKAGE_PIN Y16 [get_ports {BTN3}]
#set_property IOSTANDARD LVCMOS33 [get_ports {BTN3}]

#LEDs
#set_property PACKAGE_PIN M14 [get_ports {LED0}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED0}]
#set_property PACKAGE_PIN M15 [get_ports {LED1}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED1}]
#set_property PACKAGE_PIN G14 [get_ports {LED2}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED2}]
#set_property PACKAGE_PIN D18 [get_ports {LED3}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED3}]

#I2S Audio Codec
#set_property PACKAGE_PIN K18 [get_ports ac_bclk]
#set_property IOSTANDARD LVCMOS33 [get_ports ac_bclk]
#set_property PACKAGE_PIN T19 [get_ports ac_mclk]
#set_property IOSTANDARD LVCMOS33 [get_ports ac_mclk]
#set_property PACKAGE_PIN P18 [get_ports ac_muten]
#set_property IOSTANDARD LVCMOS33 [get_ports ac_muten]
#set_property PACKAGE_PIN M17 [get_ports ac_pbdat]
#set_property IOSTANDARD LVCMOS33 [get_ports ac_pbdat]
#set_property PACKAGE_PIN L17 [get_ports ac_pblrc]
#set_property IOSTANDARD LVCMOS33 [get_ports ac_pblrc]
#set_property PACKAGE_PIN K17 [get_ports ac_recdat]
#set_property IOSTANDARD LVCMOS33 [get_ports ac_recdat]
#set_property PACKAGE_PIN M18 [get_ports ac_reclrc]
#set_property IOSTANDARD LVCMOS33 [get_ports ac_reclrc]

#Audio Codec/external EEPROM IIC bus
#set_property PACKAGE_PIN N18 [get_ports ac_scl]
#set_property IOSTANDARD LVCMOS33 [get_ports ac_scl]
#set_property PACKAGE_PIN N17 [get_ports ac_sda]
#set_property IOSTANDARD LVCMOS33 [get_ports ac_sda]

#Additional Ethernet signals
#set_property PACKAGE_PIN F16 [get_ports eth_int_b]
#set_property IOSTANDARD LVCMOS33 [get_ports eth_int_b]
#set_property PACKAGE_PIN E17 [get_ports eth_rst_b]
#set_property IOSTANDARD LVCMOS33 [get_ports eth_rst_b]

#HDMI Signals
#set_property PACKAGE_PIN H17 [get_ports hdmi_clk_n]
#set_property IOSTANDARD TMDS_33 [get_ports hdmi_clk_n]
#set_property PACKAGE_PIN H16 [get_ports hdmi_clk_p]
#set_property IOSTANDARD TMDS_33 [get_ports hdmi_clk_p]
#set_property PACKAGE_PIN D20 [get_ports {hdmi_d_n[0]}]
#set_property IOSTANDARD TMDS_33 [get_ports {hdmi_d_n[0]}]
#set_property PACKAGE_PIN D19 [get_ports {hdmi_d_p[0]}]
#set_property IOSTANDARD TMDS_33 [get_ports {hdmi_d_p[0]}]
#set_property PACKAGE_PIN B20 [get_ports {hdmi_d_n[1]}]
#set_property IOSTANDARD TMDS_33 [get_ports {hdmi_d_n[1]}]
#set_property PACKAGE_PIN C20 [get_ports {hdmi_d_p[1]}]
#set_property IOSTANDARD TMDS_33 [get_ports {hdmi_d_p[1]}]
#set_property PACKAGE_PIN A20 [get_ports {hdmi_d_n[2]}]
#set_property IOSTANDARD TMDS_33 [get_ports {hdmi_d_n[2]}]
#set_property PACKAGE_PIN B19 [get_ports {hdmi_d_p[2]}]
#set_property IOSTANDARD TMDS_33 [get_ports {hdmi_d_p[2]}]
#set_property PACKAGE_PIN E19 [get_ports hdmi_cec]
#set_property IOSTANDARD LVCMOS33 [get_ports hdmi_cec]
#set_property PACKAGE_PIN E18 [get_ports hdmi_hpd]
#set_property IOSTANDARD LVCMOS33 [get_ports hdmi_hpd]
#set_property PACKAGE_PIN F17 [get_ports hdmi_out_en]
#set_property IOSTANDARD LVCMOS33 [get_ports hdmi_out_en]
#set_property PACKAGE_PIN G17 [get_ports hdmi_scl]
#set_property IOSTANDARD LVCMOS33 [get_ports hdmi_scl]
#set_property PACKAGE_PIN G18 [get_ports hdmi_sda]
#set_property IOSTANDARD LVCMOS33 [get_ports hdmi_sda]

#Pmod Header JA (XADC)
#set_property PACKAGE_PIN N15 [get_ports {JA1}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JA1]
#set_property PACKAGE_PIN L14 [get_ports {JA2)]
#set_property IOSTANDARD LVCMOS33 [get_ports {JA2]}]
#set_property PACKAGE_PIN K16 [get_ports {JA3}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JA3}]
#set_property PACKAGE_PIN K14 [get_ports {JA4}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JA4}]
#set_property PACKAGE_PIN N16 [get_ports {JA7}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JA7}]
#set_property PACKAGE_PIN L15 [get_ports {JA8]
#set_property IOSTANDARD LVCMOS33 [get_ports {JA8}]
#set_property PACKAGE_PIN J16 [get_ports {JA9}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JA9}]
#set_property PACKAGE_PIN J14 [get_ports {JA10]
#set_property IOSTANDARD LVCMOS33 [get_ports {JA10}]

#Pmod Header JB
#set_property PACKAGE_PIN T20 [get_ports {JB1}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JB1}]
#set_property PACKAGE_PIN U20 [get_ports {JB2}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JB2}]
#set_property PACKAGE_PIN V20 [get_ports {JB3}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JB3}]
#set_property PACKAGE_PIN W20 [get_ports {JB4}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JB4}]
#set_property PACKAGE_PIN Y18 [get_ports {JB7}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JB7}]
#set_property PACKAGE_PIN Y19 [get_ports {JB8}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JB8}]
#set_property PACKAGE_PIN W18 [get_ports {JB9}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JB9}]
#set_property PACKAGE_PIN W19 [get_ports {JB10}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JB10}]

#Pmod Header JC
#set_property PACKAGE_PIN V15 [get_ports {JC1}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JC1}]
#set_property PACKAGE_PIN W15 [get_ports {JC2}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JC2}]
#set_property PACKAGE_PIN T11 [get_ports {JC3}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JC3}]
#set_property PACKAGE_PIN T10 [get_ports {JC4}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JC4}]
#set_property PACKAGE_PIN W14 [get_ports {JC7}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JC7}]
#set_property PACKAGE_PIN Y14 [get_ports {JC8}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JC8}]
#set_property PACKAGE_PIN T12 [get_ports {JC9}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JC9}]
#set_property PACKAGE_PIN U12 [get_ports {JC10}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JC10}]

#Pmod Header JD
#set_property PACKAGE_PIN T14 [get_ports {JD1}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JD1}]
#set_property PACKAGE_PIN T15 [get_ports {JD2}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JD2}]
#set_property PACKAGE_PIN P14 [get_ports {JD3}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JD3}]
#set_property PACKAGE_PIN R14 [get_ports {JD4}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JD4}]
#set_property PACKAGE_PIN U14 [get_ports {JD7]
#set_property IOSTANDARD LVCMOS33 [get_ports {JD7}]
#set_property PACKAGE_PIN U15 [get_ports {JD8}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JD8}]
#set_property PACKAGE_PIN V17 [get_ports {JD9}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JD9}]
#set_property PACKAGE_PIN V18 [get_ports {JD10}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JD10}]

#Pmod Header JE
set_property PACKAGE_PIN V12 [get_ports {AD1sync_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD1sync_0}]
set_property PACKAGE_PIN W16 [get_ports {AD1dat1_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD1dat1_0}]
set_property PACKAGE_PIN J15 [get_ports {AD1dat2_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD1dat2_0}]
set_property PACKAGE_PIN H15 [get_ports {AD1sclk_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD1sclk_0}]
set_property PACKAGE_PIN V13 [get_ports {DA2sync_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA2sync_0}]
set_property PACKAGE_PIN U17 [get_ports {DA2dat1_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA2dat1_0}]
set_property PACKAGE_PIN T17 [get_ports {DA2dat2_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA2dat2_0}]
set_property PACKAGE_PIN Y17 [get_ports {DA2sclk_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA2sclk_0}]

#USB-OTG overcurrent detect pin
#set_property PACKAGE_PIN U13 [get_ports otg_oc]
#set_property IOSTANDARD LVCMOS33 [get_ports otg_oc]

#VGA Connector
##IO_L7P_T1_AD2P_35
#set_property PACKAGE_PIN M19 [get_ports {vga_r[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[0]}]
#set_property PACKAGE_PIN L20 [get_ports {vga_r[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[1]}]
#set_property PACKAGE_PIN J20 [get_ports {vga_r[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[2]}]
#set_property PACKAGE_PIN G20 [get_ports {vga_r[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[3]}]
#set_property PACKAGE_PIN F19 [get_ports {vga_r[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[4]}]
#set_property PACKAGE_PIN H18 [get_ports {vga_g[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[0]}]
#set_property PACKAGE_PIN N20 [get_ports {vga_g[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[1]}]
#set_property PACKAGE_PIN L19 [get_ports {vga_g[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[2]}]
#set_property PACKAGE_PIN J19 [get_ports {vga_g[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[3]}]
#set_property PACKAGE_PIN H20 [get_ports {vga_g[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[4]}]
#set_property PACKAGE_PIN F20 [get_ports {vga_g[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[5]}]
#set_property PACKAGE_PIN P20 [get_ports {vga_b[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[0]}]
#set_property PACKAGE_PIN M20 [get_ports {vga_b[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[1]}]
#set_property PACKAGE_PIN K19 [get_ports {vga_b[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[2]}]
#set_property PACKAGE_PIN J18 [get_ports {vga_b[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[3]}]
#set_property PACKAGE_PIN G19 [get_ports {vga_b[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[4]}]
#set_property PACKAGE_PIN P19 [get_ports vga_hs]
#set_property IOSTANDARD LVCMOS33 [get_ports vga_hs]
#set_property PACKAGE_PIN R19 [get_ports vga_vs]
#set_property IOSTANDARD LVCMOS33 [get_ports vga_vs]
