M48
; DRILL file {KiCad (6.0.7)} date Fri Sep  2 10:14:26 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-02T10:14:26-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0276
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0394
%
G90
G05
T1
X4.2839Y-3.9665
X4.2839Y-4.2665
T2
X3.9967Y-4.1299
X4.0967Y-4.1299
T3
X4.726Y-4.0346
X4.726Y-4.2118
X4.9819Y-4.0346
X4.9819Y-4.2118
T0
M30
